# use the Python 3.5 language
language: python
python:
  - "3.5"

# cache to improve build speed
cache:
  directories:
    - $HOME/.pip-cache/

# install mdl for checking Markdown
before_install:
  - gem install mdl

# command to install dependencies
install:
  - pip install --upgrade pip
  - python3 -m pip install -r duplicates/requirements.txt

# perform testing:
# --> run the internal test suite with pytest
# --> demonstrate the use of gatorgrader.py on itself
script:
  - pytest duplicates/tests
  - mdl README.md
